# Generated by Django 6.0.7 on 2026-07-13 23:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(help_text='Somente números ou no formato 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cargo', models.CharField(max_length=60, verbose_name='Cargo')),
                ('setor', models.CharField(max_length=60, verbose_name='Setor')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'colaborador',
                'verbose_name_plural': 'colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do EPI')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('CABECA', 'Proteção da cabeça'), ('AUDITIVA', 'Proteção auditiva'), ('RESPIRATORIA', 'Proteção respiratória'), ('VISUAL', 'Proteção visual'), ('MAOS', 'Proteção das mãos'), ('PES', 'Proteção dos pés'), ('TRONCO', 'Proteção do tronco'), ('ALTURA', 'Trabalho em altura'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('ca_numero', models.CharField(help_text='Certificado de Aprovação (NR-6)', max_length=20, verbose_name='Nº do CA')),
                ('ca_validade', models.DateField(verbose_name='Validade do CA')),
                ('tamanho', models.CharField(blank=True, max_length=10, verbose_name='Tamanho')),
                ('qtd_estoque', models.PositiveIntegerField(default=0, verbose_name='Qtde. em estoque')),
                ('qtd_minima', models.PositiveIntegerField(default=5, verbose_name='Estoque mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perfil', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('TECNICO', 'Técnico de Segurança'), ('ALMOXARIFE', 'Almoxarife')], default='TECNICO', max_length=20, verbose_name='Perfil de acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data do empréstimo')),
                ('data_prevista_devolucao', models.DateField(verbose_name='Data prevista de devolução')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='core.colaborador', verbose_name='Colaborador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'empréstimo',
                'verbose_name_plural': 'empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
        migrations.CreateModel(
            name='ItemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('data_devolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data da devolução')),
                ('condicao_devolucao', models.CharField(blank=True, choices=[('BOM_ESTADO', 'Bom estado'), ('DANIFICADO', 'Danificado'), ('EXTRAVIADO', 'Extraviado')], max_length=12, verbose_name='Condição na devolução')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.emprestimo')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_emprestados', to='core.epi', verbose_name='EPI')),
            ],
            options={
                'verbose_name': 'item do empréstimo',
                'verbose_name_plural': 'itens do empréstimo',
            },
        ),
    ]
